// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuo6AJMFqnzsOI1dxs_JVuv4jWPtqNmNg',
    appId: '1:928639306481:web:764fd6bc73946b74f77750',
    messagingSenderId: '928639306481',
    projectId: 'todolistapp-886b7',
    authDomain: 'todolistapp-886b7.firebaseapp.com',
    storageBucket: 'todolistapp-886b7.firebasestorage.app',
    measurementId: 'G-BB98GW356P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH6TwGs2NNZNP_3m7A2WPlWNmvapuISwQ',
    appId: '1:928639306481:android:654b05b760fe78dff77750',
    messagingSenderId: '928639306481',
    projectId: 'todolistapp-886b7',
    storageBucket: 'todolistapp-886b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBArNJnb-thkdkR3VO7YmAldNtdXRCPztc',
    appId: '1:928639306481:ios:0fb9cf481e99101af77750',
    messagingSenderId: '928639306481',
    projectId: 'todolistapp-886b7',
    storageBucket: 'todolistapp-886b7.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBArNJnb-thkdkR3VO7YmAldNtdXRCPztc',
    appId: '1:928639306481:ios:0fb9cf481e99101af77750',
    messagingSenderId: '928639306481',
    projectId: 'todolistapp-886b7',
    storageBucket: 'todolistapp-886b7.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuo6AJMFqnzsOI1dxs_JVuv4jWPtqNmNg',
    appId: '1:928639306481:web:c90d8b30c30e7634f77750',
    messagingSenderId: '928639306481',
    projectId: 'todolistapp-886b7',
    authDomain: 'todolistapp-886b7.firebaseapp.com',
    storageBucket: 'todolistapp-886b7.firebasestorage.app',
    measurementId: 'G-T11DHN552T',
  );

}